### ISSUE TITLE
Problem getting an image

### ISSUE THREAD

**Issue by djmaze** [pulumi/pulumi-hcloud#221]
### What happened?

Tried to create server using `image: "ubuntu.22.04"` as shown in the plugin documentation. Got the error message `more than one Image found for name ubuntu-22.04`.

Looked at the terraform provider and tried the following approach instead:
```javascript
let image = hcloud.getImage({
    name: "ubuntu-22.04",
    withArchitecture: "x86"
})
// const server = new hcloud.Server("test", {
//    image: image.then(img => img.id.toString()),
//    // ...
// }
```

Now getting the following error:

```
    error: Running program '/home/test/mail_infrastructure/' failed with an unhandled exception:
    Error: Invoke of 'hcloud:index/getImage:getImage' failed: Invalid or unknown key ()
        at deserializeResponse (/home/test/mail_infrastructure/node_modules/@pulumi/runtime/invoke.ts:235:15)
        at /home/test/mail_infrastructure/node_modules/@pulumi/runtime/invoke.ts:182:16
        at Generator.next (<anonymous>)
        at fulfilled (/home/test/mail_infrastructure/node_modules/@pulumi/pulumi/runtime/invoke.js:18:58)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### Expected Behavior

The server should be created with the correct x86 image.

### Steps to reproduce

Create a pulumi typescript project. Add the `hcloud` plugin (using `npm i @pulumi/hcloud`) and add the following code:

```javascript
let image = hcloud.getImage({
    name: "ubuntu-22.04",
    withArchitecture: "x86"
})
```

### Output of `pulumi about`

```
CLI
Version      3.69.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME    VERSION
hcloud  1.12.0
nodejs  unknown

Host     
OS       nixos
Version  22.11 (Raccoon)
Arch     x86_64

This project is written in nodejs: executable='/home/myuser/.nix-profile/bin/node' version='v14.21.3'

Current Stack: dev

TYPE                            URN
pulumi:pulumi:Stack             urn:pulumi:dev::mail_infrastructure::pulumi:pulumi:Stack::mail_infrastructure-dev
pulumi:providers:hcloud         urn:pulumi:dev::mail_infrastructure::pulumi:providers:hcloud::default_1_12_0
hcloud:index/firewall:Firewall  urn:pulumi:dev::mail_infrastructure::hcloud:index/firewall:Firewall::mail
hcloud:index/sshKey:SshKey      urn:pulumi:dev::mail_infrastructure::hcloud:index/sshKey:SshKey::myuser


Found no pending operations associated with dev

Backend        
Name           myhost
URL            file://./.pulumi-state
User           myuser
Organizations  

Dependencies:
NAME            VERSION
@pulumi/hcloud  1.12.0
@pulumi/pulumi  3.69.0
@types/node     16.18.34
```

### Additional context

Not sure if this is related, but pulumi also outputs strange warnings:

```
warning: resource plugin hcloud is expected to have version >=1.12.0, but has 1.10.1; the wrong version may be on your path, or this may be a bug in the plugin
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
Hey @djmaze, this definitely looks like an unusual issue involving the local environment. Is there a binary called `pulumi-resource-hcloud` on your path? I installed the latest SDK via Pulumi and (1.12.0) and this worked.

The output of these commands would be helpful:

```shell
which pulumi-resource-hcloud
pulumi plugin ls | grep hcloud
ls ~/.pulumi/plugins | grep hcloud
```

**Comment by djmaze** [comment]
Sorry for the late response. I had a system installation as well as a local user installation of pulumi, which was probably the culprit. Cleaned that up and it seems to work now.
