### ISSUE TITLE
v1.20.2 broke my pulumi project

### ISSUE THREAD

**Issue by tsndr** [pulumi/pulumi-hcloud#603]
### Describe what happened

When running `pulumi preview` after upgrading from `v1.20.1` to `v1.20.2` I'm getting the following error:

![Image](https://github.com/user-attachments/assets/2c18890b-990f-4612-b6ae-77c906f255aa)

Am I doing something wrong or could this actually be a bug?

### Sample program

```typescript
import { SshKey } from "@pulumi/hcloud"

new SshKey("macbook-air", {
	name: "MacBook Air",
	publicKey: "ssh-ed25519 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
})
```

### Log output

```
Previewing update (prod):
     Type                    Name         Plan     Info
     pulumi:pulumi:Stack     infra-prod            24 messages
     └─ hcloud:index:SshKey  macbook-air           1 error

Diagnostics:
  pulumi:pulumi:Stack (infra-prod):
    panic: fatal: An assertion has failed: The bridge does not accept secrets, so we should not encounter them here
    goroutine 93 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x80?, {0x4dee0d4?, 0xc00061e4c0?}, {0x0?, 0xc000180008?, 0xc00158c058?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/go/common/util/contract/assert.go:35 +0xe8
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*ConfigEncoding).UnfoldProperties(0xc00158c058, 0xc0005e31a0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.91.0/pkg/tfbridge/config_encoding.go:143 +0x2b2
    github.com/pulumi/pulumi-terraform-bridge/pf/internal/configencoding.(*provider[...]).ConfigureWithContext(0xc000b8cb80, {0x5b1f488?, 0xc0005e2fc0}, 0xc0005e31a0)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.0/internal/configencoding/provider.go:110 +0x45
    github.com/pulumi/pulumi-terraform-bridge/pf/internal/plugin.(*provider).Configure(0x5ab61e0?, {0x5b1f488?, 0xc0005e2fc0?}, {0x0?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.0/internal/plugin/provider_context.go:143 +0x25
    github.com/pulumi/pulumi-terraform-bridge/pf/internal/plugin.providerThunk.Configure({{0x5b3e630?, 0xc00160ee30?}}, {0x5b1f488, 0xc0005e2fc0}, {0xffffffffffffffff?})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.0/internal/plugin/provider_server.go:83 +0x76
    github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*providerServer).Configure(0xc001684c30, {0x5b1f488, 0xc0005e2fc0}, 0xc000e0f580)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.133.0/go/common/resource/plugin/provider_server.go:346 +0x331
    github.com/pulumi/pulumi-terraform-bridge/pf/internal/plugin.(*providerServer).Configure(0x5aff4e0?, {0x5b1f488?, 0xc0005e2fc0?}, 0x0?)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/pf@v0.44.0/internal/plugin/provider_server.go:57 +0x25
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.(*muxer).Configure.func1()
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:298 +0x6f
    github.com/pulumi/pulumi-terraform-bridge/x/muxer.asyncJoin[...].func1()
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:595 +0x42
    created by github.com/pulumi/pulumi-terraform-bridge/x/muxer.asyncJoin[...] in goroutine 91
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/x/muxer@v0.0.8/muxer.go:594 +0x79

  hcloud:index:SshKey (macbook-air):
    error: error reading from server: EOF
```

### Output of `pulumi about`

```
CLI
Version      3.133.0
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.52.0
resource  awsx        2.15.0
resource  cloudflare  5.39.0
resource  docker      4.5.1
resource  docker      3.6.1
resource  hcloud      1.20.2
language  nodejs      unknown

Host
OS       darwin
Version  15.0
Arch     x86_64

Dependencies:
NAME                VERSION
@pulumi/aws         6.52.0
@pulumi/awsx        2.15.0
@pulumi/cloudflare  5.39.0
@pulumi/hcloud      1.20.2
@pulumi/pulumi      3.133.0
@types/node         22.5.5
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
hi @tsndr - thank you for reporting this issue.

This is in fact a bug in the pulumi-terraform bridge we are actively working on. 
See also: https://github.com/pulumi/pulumi-gcp/issues/2405.

We hope to have a fix soon.

**Comment by guineveresaenger** [comment]
Update: We've addressed the issue in the pulumi-terraform-bridge, and will be having a patch release here for you soon.

We apologize for the trouble and hope you'll give the new version a try as soon as it's out! 💟

**Comment by tsndr** [comment]
Thank you so much for quickly taking action <3

**Comment by eBeyond** [comment]
The issue seems to be fixed on bridge-side. Now we need a release, I think. ;)

**Comment by guineveresaenger** [comment]
Hi @eBeyond - please try v1.20.4 of this provider; it should resolve your issue. 

Thank you for your patience, and apologies for the trouble here. 🙇‍♀
